sudo: required
services:
  - docker

before_install:
  - docker build -t josefruzicka/docker-react -f Dockerfile.dev .

script:
  - docker run josefruzicka/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: : "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-312258424663"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"